---
# tasks file for prereqs
- name: Garantindo os pacotes basicos para o bluegreen
  package:
   name:
    - docker-ce
    - nginx
    - python-pip

- name: Instalando o docker-py
  pip:
   name: docker-py

- name: Garantindo os servicos do docker e nginx rodando
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker
